[package]
name = "teensy_blink"
version = "0.1.0"
authors = ["Thomas Campistron <irevoire@hotmail.fr>"]
edition = "2018"

[dependencies]

[dependencies.teensy]
git = "https://github.com/irevoire/teensy.git"
default-features = false
features = ["manual_init"]
